# Generated by Django 5.2.6 on 2025-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careercategory',
            options={'ordering': ['order', 'display_name_ru'], 'verbose_name': 'Категория карьеры', 'verbose_name_plural': 'Категории карьеры'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name_ru'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.RemoveField(
            model_name='careercategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='careercategory',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='careercategory',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='careercategory',
            name='display_name_ky',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='department',
            name='short_name_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='short_name_ky',
        ),
        migrations.RemoveField(
            model_name='department',
            name='short_name_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='contact_person_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='contact_person_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='contact_person_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='education_level_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='experience_years_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='short_description_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='tags_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='tags_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_ky',
        ),
        migrations.AddField(
            model_name='careercategory',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание категории (кыргызский)'),
        ),
        migrations.AddField(
            model_name='careercategory',
            name='display_name_kg',
            field=models.CharField(default='not given', max_length=100, verbose_name='Название для отображения (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание подразделения (кыргызский)'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Руководитель (английский)'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Руководитель (кыргызский)'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Руководитель (русский)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_kg',
            field=models.CharField(default='not given', max_length=200, verbose_name='Название подразделения (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_kg',
            field=models.TextField(blank=True, help_text='Каждое условие с новой строки', verbose_name='Условия работы (кыргызский)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_kg',
            field=models.TextField(default='not given', verbose_name='Полное описание (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='education_level_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Требования к образованию (кыргызский)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_years_kg',
            field=models.CharField(blank=True, max_length=50, verbose_name='Опыт работы (кыргызский)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location_kg',
            field=models.CharField(default='Бишкек', max_length=100, verbose_name='Место работы (кыргызский)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_kg',
            field=models.TextField(default='not given', help_text='Каждое требование с новой строки', verbose_name='Требования (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities_kg',
            field=models.TextField(default='not given', help_text='Каждое обязательство с новой строки', verbose_name='Обязанности (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_description_kg',
            field=models.TextField(default='not given', verbose_name='Краткое описание (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_kg',
            field=models.CharField(default='not given', max_length=200, verbose_name='Название вакансии (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careercategory',
            name='description_en',
            field=models.TextField(blank=True, default='not given', verbose_name='Описание категории (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careercategory',
            name='description_ru',
            field=models.TextField(blank=True, default='not given', verbose_name='Описание категории (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careercategory',
            name='display_name_en',
            field=models.CharField(default='not given', max_length=100, verbose_name='Название для отображения (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careercategory',
            name='display_name_ru',
            field=models.CharField(default='not given', max_length=100, verbose_name='Название для отображения (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, default='not given', verbose_name='Описание подразделения (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ru',
            field=models.TextField(blank=True, default='not given', verbose_name='Описание подразделения (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name_en',
            field=models.CharField(default='not given', max_length=200, verbose_name='Название подразделения (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name_ru',
            field=models.CharField(default='not given', max_length=200, verbose_name='Название подразделения (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions_en',
            field=models.TextField(blank=True, default='not given', help_text='Каждое условие с новой строки', verbose_name='Условия работы (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions_ru',
            field=models.TextField(blank=True, default='not given', help_text='Каждое условие с новой строки', verbose_name='Условия работы (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(default='not given', verbose_name='Полное описание (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(default='not given', verbose_name='Полное описание (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education_level_en',
            field=models.CharField(blank=True, default='not given', max_length=200, verbose_name='Требования к образованию (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education_level_ru',
            field=models.CharField(blank=True, default='not given', max_length=200, verbose_name='Требования к образованию (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience_years_en',
            field=models.CharField(blank=True, default='not given', max_length=50, verbose_name='Опыт работы (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience_years_ru',
            field=models.CharField(blank=True, default='not given', max_length=50, verbose_name='Опыт работы (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_en',
            field=models.CharField(default='Bishkek', max_length=100, verbose_name='Место работы (английский)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_ru',
            field=models.CharField(default='Бишкек', max_length=100, verbose_name='Место работы (русский)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements_en',
            field=models.TextField(default='not given', help_text='Каждое требование с новой строки', verbose_name='Требования (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements_ru',
            field=models.TextField(default='not given', help_text='Каждое требование с новой строки', verbose_name='Требования (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities_en',
            field=models.TextField(default='not given', help_text='Каждое обязательство с новой строки', verbose_name='Обязанности (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities_ru',
            field=models.TextField(default='not given', help_text='Каждое обязательство с новой строки', verbose_name='Обязанности (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description_en',
            field=models.TextField(default='not given', verbose_name='Краткое описание (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description_ru',
            field=models.TextField(default='not given', verbose_name='Краткое описание (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(default='not given', max_length=200, verbose_name='Название вакансии (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(default='not given', max_length=200, verbose_name='Название вакансии (русский)'),
            preserve_default=False,
        ),
    ]
