# Generated by Django 5.2.6 on 2025-09-05 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('summary', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('author', models.CharField(default='Администрация университета', max_length=100, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('news', 'Новости'), ('events', 'События'), ('announcements', 'Объявления')], max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slug')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет (hex)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('event_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('event_category', models.CharField(choices=[('conference', 'Конференция'), ('open-day', 'День открытых дверей'), ('competition', 'Конкурс'), ('ceremony', 'Церемония'), ('workshop', 'Мастер-класс'), ('seminar', 'Семинар'), ('lecture', 'Лекция')], max_length=50, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящее'), ('ongoing', 'Текущее'), ('past', 'Прошедшее'), ('cancelled', 'Отменено')], default='upcoming', max_length=20, verbose_name='Статус')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум участников')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущее количество участников')),
                ('registration_required', models.BooleanField(default=False, verbose_name='Требуется регистрация')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок регистрации')),
                ('registration_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на регистрацию')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.CharField(choices=[('academic', 'Учебное'), ('scholarship', 'Стипендия'), ('schedule', 'Расписание'), ('competition', 'Конкурс'), ('health', 'Здоровье'), ('technical', 'Техническое'), ('administrative', 'Административное')], max_length=50, verbose_name='Тип объявления')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('is_deadline_approaching', models.BooleanField(default=False, verbose_name='Приближается дедлайн')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/attachments/', verbose_name='Вложение')),
                ('attachment_name', models.CharField(blank=True, max_length=100, verbose_name='Название вложения')),
                ('target_students', models.BooleanField(default=True, verbose_name='Для студентов')),
                ('target_staff', models.BooleanField(default=False, verbose_name='Для сотрудников')),
                ('target_faculty', models.BooleanField(default=False, verbose_name='Для преподавателей')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_details', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-priority', '-deadline'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='NewsTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='news.news')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.newstag')),
            ],
            options={
                'verbose_name': 'Связь новости с тегом',
                'verbose_name_plural': 'Связи новостей с тегами',
                'unique_together': {('news', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_views', to='news.news')),
            ],
            options={
                'verbose_name': 'Просмотр новости',
                'verbose_name_plural': 'Просмотры новостей',
                'unique_together': {('news', 'ip_address')},
            },
        ),
    ]
