# Generated by Django 5.2.6 on 2025-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Полное содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Полное содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Полное содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_ky',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название тега'),
        ),
    ]
