# Generated by Django 5.2.6 on 2025-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_content_en_news_content_ky_news_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='name_ky',
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(default='not given', max_length=200, verbose_name='Место проведения (английский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_kg',
            field=models.CharField(default='not given', max_length=200, verbose_name='Место проведения (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(default='not given', max_length=200, verbose_name='Место проведения (русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='author_en',
            field=models.CharField(default='University Administration', max_length=100, verbose_name='Автор (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_kg',
            field=models.CharField(default='Университеттин администрациясы', max_length=100, verbose_name='Автор (кыргызский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_ru',
            field=models.CharField(default='Администрация университета', max_length=100, verbose_name='Автор (русский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kg',
            field=models.TextField(default='not given', verbose_name='Полное содержание (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='summary_kg',
            field=models.TextField(default='not given', max_length=500, verbose_name='Краткое описание (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_kg',
            field=models.CharField(default='not given', max_length=200, verbose_name='Заголовок (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание (кыргызский)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(default='not given', max_length=100, verbose_name='Название (английский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_kg',
            field=models.CharField(default='not given', max_length=100, verbose_name='Название (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(default='not given', max_length=100, verbose_name='Название (русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newstag',
            name='name_kg',
            field=models.CharField(default='not given', max_length=50, verbose_name='Название тега (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(default='not given', verbose_name='Полное содержание (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(default='not given', verbose_name='Полное содержание (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='summary_en',
            field=models.TextField(default='not given', max_length=500, verbose_name='Краткое описание (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='summary_ru',
            field=models.TextField(default='not given', max_length=500, verbose_name='Краткое описание (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='not given', max_length=200, verbose_name='Заголовок (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default='not given', max_length=200, verbose_name='Заголовок (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newstag',
            name='name_en',
            field=models.CharField(default='not given', max_length=50, verbose_name='Название тега (английский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newstag',
            name='name_ru',
            field=models.CharField(default='not given', max_length=50, verbose_name='Название тега (русский)'),
            preserve_default=False,
        ),
    ]
