# Generated by Django 5.2.6 on 2025-09-06 05:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название центра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Научный центр',
                'verbose_name_plural': 'Научные центры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название публикации')),
                ('journal', models.CharField(max_length=255, verbose_name='Журнал')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год публикации')),
                ('citation_index', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Индекс цитирования')),
                ('doi', models.CharField(blank=True, max_length=100, unique=True, verbose_name='DOI')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='publications.researchcenter', verbose_name='Научный центр')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-year', '-citation_index'],
                'indexes': [models.Index(fields=['year'], name='publication_year_7f8d21_idx'), models.Index(fields=['citation_index'], name='publication_citatio_a639b0_idx'), models.Index(fields=['journal'], name='publication_journal_3e81f2_idx')],
            },
        ),
    ]
