# Generated by Django 5.2.6 on 2025-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='organization',
        ),
        migrations.AddField(
            model_name='grant',
            name='organization_en',
            field=models.CharField(default='не указано', max_length=200, verbose_name='Организация (англ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='organization_kg',
            field=models.CharField(default='берилбеген', max_length=200, verbose_name='Организация (кыр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='organization_ru',
            field=models.CharField(default='не указано', max_length=200, verbose_name='Организация (рус)'),
            preserve_default=False,
        ),
    ]
