# Generated by Django 5.2.6 on 2025-09-08 10:52

from django.db import migrations


def migrate_organization_data(apps, schema_editor):
    """Перенос данных из старого поля organization в новые поля с переводами"""
    Grant = apps.get_model('research', 'Grant')
    
    # Получаем все гранты
    for grant in Grant.objects.all():
        # Если новые поля пустые (значение по умолчанию "Не указано"), 
        # но есть данные в старом формате, переносим их
        if grant.organization_ru == "Не указано":
            # Здесь мы предполагаем, что старые данные были на русском языке
            # В реальности нужно будет проанализировать данные и правильно их распределить
            grant.organization_ru = "Необходимо обновить"  # Заменить на реальные данные
            grant.organization_en = "Need to update"  # Заменить на реальные данные  
            grant.organization_kg = "Жаңылоо керек"  # Заменить на реальные данные
            grant.save()


def reverse_migrate_organization_data(apps, schema_editor):
    """Обратная операция - восстановление старых данных (не применимо в данном случае)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_remove_grant_organization_grant_organization_en_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_organization_data, reverse_migrate_organization_data),
    ]
