# Generated by Django 5.2.6 on 2025-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20250908_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_en',
            field=models.CharField(default='not given', max_length=500, verbose_name='Авторы (англ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_kg',
            field=models.CharField(default='берилбеген', max_length=500, verbose_name='Авторы (кыр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_ru',
            field=models.CharField(default='не указано', max_length=500, verbose_name='Авторы (рус)'),
            preserve_default=False,
        ),
    ]
