# Generated by Django 5.2.6 on 2025-09-08 11:04

from django.db import migrations


def migrate_authors_data(apps, schema_editor):
    """Перенос данных авторов из старого формата в новые поля с переводами"""
    Publication = apps.get_model('research', 'Publication')
    
    # Получаем все публикации
    for publication in Publication.objects.all():
        # Если новые поля содержат значения по умолчанию, 
        # обновляем их на более осмысленные значения
        if (publication.authors_ru == "не указано" and 
            publication.authors_en == "not given" and 
            publication.authors_kg == "берилбеген"):
            
            # В реальности здесь нужно будет проанализировать старые данные
            # и правильно их распределить по языкам
            publication.authors_ru = "Необходимо обновить авторов"
            publication.authors_en = "Need to update authors"
            publication.authors_kg = "Авторлорду жаңылоо керек"
            publication.save()


def reverse_migrate_authors_data(apps, schema_editor):
    """Обратная операция"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_remove_publication_authors_publication_authors_en_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_authors_data, reverse_migrate_authors_data),
    ]
