# Generated by Django 5.2.6 on 2025-09-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20250908_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchcenter',
            name='director',
        ),
        migrations.AddField(
            model_name='researchcenter',
            name='director_en',
            field=models.CharField(default='надо поменять значени', max_length=200, verbose_name='Директор (англ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchcenter',
            name='director_kg',
            field=models.CharField(default='need to change the value', max_length=200, verbose_name='Директор (кыр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchcenter',
            name='director_ru',
            field=models.CharField(default='маалыматты алмаштырыш керек', max_length=200, verbose_name='Директор (рус)'),
            preserve_default=False,
        ),
    ]
