# Generated by Django 5.2.6 on 2025-09-08 11:14

from django.db import migrations


def migrate_director_data(apps, schema_editor):
    """Перенос данных директоров из старого формата в новые поля с переводами"""
    ResearchCenter = apps.get_model('research', 'ResearchCenter')
    
    # Получаем все исследовательские центры
    for center in ResearchCenter.objects.all():
        # Если новые поля содержат значения по умолчанию, 
        # обновляем их на более осмысленные значения
        if (center.director_ru == "маалыматты алмаштырыш керек" and 
            center.director_en == "надо поменять значени" and 
            center.director_kg == "need to change the value"):
            
            # В реальности здесь нужно будет проанализировать старые данные
            # и правильно их распределить по языкам
            center.director_ru = "Необходимо обновить директора"
            center.director_en = "Need to update director"
            center.director_kg = "Директорду жаңылоо керек"
            center.save()


def reverse_migrate_director_data(apps, schema_editor):
    """Обратная операция"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_researchcenter_director_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_director_data, reverse_migrate_director_data),
    ]
