# Generated by Django 4.2.8 on 2025-09-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (английский)')),
                ('subtitle_ru', models.CharField(max_length=300, verbose_name='Подзаголовок (русский)')),
                ('subtitle_kg', models.CharField(max_length=300, verbose_name='Подзаголовок (кыргызский)')),
                ('subtitle_en', models.CharField(max_length=300, verbose_name='Подзаголовок (английский)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
    ]
